In [1]:
import pandas as pd
import numpy as np
import random

### GENERATE AN INPUT ARRAY

In [2]:
inputs = pd.DataFrame(
    {"x1": [0,1,0,1], "x2": [0,0,1,1], "bias": [3,3,3,3]}
).to_numpy()

In [3]:
inputs

array([[0, 0, 3],
       [1, 0, 3],
       [0, 1, 3],
       [1, 1, 3]])

### GENERATE AN OUTPUT ARRAY

In [4]:
outputs = pd.DataFrame(
    {"y": [1,1,1,0]}
).to_numpy()

In [5]:
outputs

array([[1],
       [1],
       [1],
       [0]])

### GENERATE AN INITIAL SET OF WEIGHTS

In [6]:
weights = pd.DataFrame(
    {"weights": [random.uniform(-0.2, 0.25) for i in range(3)]}
).to_numpy()

In [7]:
weights

array([[-0.02096727],
       [ 0.04315872],
       [ 0.20232374]])

### DEFINE ACTIVATION & DERIVATIVE FUNCTIONS

In [8]:
# Sigmoid function to serve as activation function
def sigmoid(arr: np.array):
    return 1/(1+np.exp(-arr))

# Derivative of the sigmoid function for use in updating weights
def sigmoid_derivative(arr: np.array):
    sx = sigmoid(arr)
    return sx * (1 - sx)

### DEFINE THE ITERATION PROCESS

In [9]:
for iteration in range(50000):
    # WEIGHTED SUM OF INPUTS & WEIGHTS
    weighted_sum = np.dot(inputs, weights)
    
    # ACTIVATE OUTPUTS
    activate_output = sigmoid(weighted_sum)
    
    # CALCULATE ERROR ADJUSTMENTS
    error = outputs - activate_output
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # TWEAK WEIGHTS
    weights += np.dot(inputs.T, adjustments)

In [10]:
print("Weights after training")
print(weights)

print("Output after training")
print(activate_output)

Weights after training
[[-10.32126009]
 [-10.32126009]
 [  5.21266623]]
Output after training
[[0.99999984]
 [0.99511519]
 [0.99511519]
 [0.00666293]]
