In [32]:
# Generate test data
import numpy as np

np.random.seed(42)

# Construct an array of lists (??)
# Assume this is 4 instances of 3 inputs
inputs = np.array([
    [0, 0],
    [1, 0],
    [0, 1],
    [1, 1]
])

target_outputs = [
    [1],
    [1],
    [1],
    [0]
]

In [33]:
# Define a Sigmoid activation function 
def sigmoid(x):
    sgmd = 1 / (1 + np.exp(-x))
    return sgmd

# Calculate the derivative of sigmoid at a passed value (rate of change at point x)
def deriv_sigmoid(x):
    sgmd = sigmoid(x)
    dtv  = sgmd * (1 - sgmd)
    return dtv

In [34]:
sigmoid(.0001)

0.5000249999999792

In [35]:
deriv_sigmoid(-1)

0.19661193324148185

In [36]:
deriv_sigmoid(.00000001)

0.25

In [37]:
# Generate some initial random weights
import random
random.seed(42)

wgts = []
for i in range(2):
    wgts.append([random.uniform(-1.0, 1.0)])
    
wgts = np.array(wgts)
wgts

array([[ 0.2788536 ],
       [-0.94997849]])

In [38]:
# Calculate weighted sum of inputs (input vector) and weights [a dot product]
wght_sum = np.dot(inputs, wgts)
wght_sum

array([[ 0.        ],
       [ 0.2788536 ],
       [-0.94997849],
       [-0.67112489]])

In [39]:
# Output the activated value of Epoch 1 (network iteration #1?)
activated_output = sigmoid(wght_sum)
activated_output

array([[0.5       ],
       [0.56926515],
       [0.27888915],
       [0.338245  ]])

In [40]:
error = target_outputs - activated_output
error

array([[ 0.5       ],
       [ 0.43073485],
       [ 0.72111085],
       [-0.338245  ]])

In [41]:
# Calculate weight adjustment factors
adjustments = error * deriv_sigmoid(wght_sum)
adjustments

array([[ 0.125     ],
       [ 0.10561719],
       [ 0.1450226 ],
       [-0.07571118]])

In [42]:
# Calculate adjusted weights 
wgts += np.dot(inputs.T, adjustments)
wgts

array([[ 0.30875961],
       [-0.88066707]])

In [45]:
# Step through this process with multiple epochs (network iterations)
for iteration in range(50):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, wgts)
    
    # Apply the sigmoid function to activate outputs
    activated_output = sigmoid(weighted_sum)
    
    # Calculate error
    error = target_outputs - activated_output
    
    # Calculate weight adjustments
    adjustments = error * deriv_sigmoid(weighted_sum)
    
    # Generate adjusted weights
    wgts += np.dot(inputs.T, adjustments)
    

print("Weights after training")
print(wgts)

print("Output after training")
print(activated_output)

Weights after training
[[ 1.38777878e-16]
 [-3.19189120e-16]]
Output after training
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
