In [146]:
import typing
import numpy as np
import pandas as pd
import random

In [147]:
np.random.seed(812)

In [148]:
inputs = np.array([
    [0,0,1],
    [1,1,1],
    [1,0,1],
    [0,1,1]
])

correct_outputs = [
    [0],
    [1],
    [1],
    [0]
]
correct_outputs

[[0], [1], [1], [0]]

In [149]:
# Sigmoid function to serve as activation function
def sigmoid(arr: np.array):
    return 1/(1+np.exp(-arr))

# Derivative of the sigmoid function for use in updating weights
def sigmoid_derivative(arr: np.array):
    sx = sigmoid(arr)
    return sx * (1 - sx)

In [116]:
# Create a numpy array of a column of random weights
arr_weights = pd.DataFrame(
    {"weights": [random.uniform(-0.333, 0.5) for i in range(3)]}
).to_numpy()

arr_weights

array([[-0.27389341],
       [-0.17850996],
       [-0.29967398]])

In [150]:
# TEMP: override weights for now
arr_weights = pd.DataFrame(
    {"weights": [0.0099616, 0.21185521, -0.08502562]}
).to_numpy()

arr_weights

array([[ 0.0099616 ],
       [ 0.21185521],
       [-0.08502562]])

In [151]:
# Calculate the weighted sum of inputs and weights (dot product of inputs x weights)
weighted_sum = np.dot(inputs, arr_weights)
weighted_sum

array([[-0.08502562],
       [ 0.13679119],
       [-0.07506402],
       [ 0.12682959]])

In [152]:
# Activate the outputs (end of Epoch 1)
output_activated = sigmoid(weighted_sum)

output_activated

array([[0.47875639],
       [0.53414457],
       [0.4812428 ],
       [0.53166496]])

In [153]:
# Calculate error between actuals and activated outputs
error = correct_outputs - output_activated
error

array([[-0.47875639],
       [ 0.46585543],
       [ 0.5187572 ],
       [-0.53166496]])

In [154]:
sigmoid_derivative(weighted_sum)

array([[0.24954871],
       [0.24883415],
       [0.24964817],
       [0.24899733]])

In [155]:
# Calculate the weight adjustment factors using gradient descent (sigmoid derivative of the weighted sum)
adjustments = error * sigmoid_derivative(weighted_sum)
adjustments

array([[-0.11947304],
       [ 0.11592074],
       [ 0.12950678],
       [-0.13238316]])

In [156]:
# Adjust the weights for the next Epoch (weights + [dot product of transposed inputs x weight adjustments])
arr_weights += np.dot(inputs.T, adjustments)
arr_weights

array([[ 0.25538912],
       [ 0.19539279],
       [-0.09145429]])

In [159]:
# Iterate through the process (Epochs) 10,000 times
for iteration in range(10000):
    # WEIGHTED SUM OF INPUTS & WEIGHTS
    weighted_sum = np.dot(inputs, arr_weights)
    
    # ACTIVATE
    activated_output = sigmoid(weighted_sum)
    
    # Calculate error adjustments 
    error = correct_outputs - activated_output
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update weights
    arr_weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(arr_weights)

print("Output after training")
print(activated_output)

Weights after training
[[ 9.67294482]
 [-0.20827865]
 [-4.62935297]]
Output after training
[[0.00966721]
 [0.99211801]
 [0.99359048]
 [0.00786388]]
